### PR TITLE
Try to add Python 2.x Windows support

### PR DESCRIPTION
**Pull request by jakirkham**
Fixes https://github.com/conda-forge/psutil-feedstock/issues/3

This will probably fail due to this upstream issue ( ~~https://github.com/conda/conda-build/issues/830~~ ) ( https://github.com/conda/conda/issues/2079 ). However, it would be nice to have a build here to show people and try potential fixes on.

### CODE REVIEW

**Comment by jakirkham** [comment]
As Windows only fails on Python 2.7, I'm inclined to skip Python 2.7 on Windows and get the rest of these binaries out there. That way, people can start using this with Python 3.4 and 3.5 on Windows if they want and we can sort out Python 2.7 separately.

**Comment by jakirkham** [comment]
Rebased after merging Python 3.x Windows support from this PR ( https://github.com/conda/conda-build/issues/830 ).

**Comment by jakirkham** [comment]
Unsurprisingly this still fails on Python 2.x. Though as we have separated out the working portions, this should make it easier for someone to play with `conda-build` and this problem.

**Comment by pelson** [comment]
Do you know how we are getting on with the linked issue? I'm happy enough to completely rule out py2k if necessary.

**Comment by jakirkham** [comment]
> Do you know how we are getting on with the linked issue?

It is a weird Windows issue involving moving files when they are in use. See this issue ( https://github.com/conda/conda/issues/2079 ). I believe there is a workaround, but I don't totally follow it. Maybe @msarahan can help us out.

> I'm happy enough to completely rule out py2k if necessary.

I'm not. I still need Python 2.x for some things. That being said, we do have Python 3.x on all platforms here and Python 2.x on *NIXes. This largely handles my issues. Though Python 2.x support on Windows is desirable.

**Comment by jakirkham** [comment]
Take a look at this [gitter convo]( https://gitter.im/conda-forge/conda-forge.github.io?at=572be7a6d6d0f60219f1034f ) for more details. Basically, we can come up with a workaround, but it's going to have involve multiple miniconda installs and may just not be fun to work with.

**Comment by jakirkham** [comment]
Rebasing to see if this might now work.

**Comment by jakirkham** [comment]
Woot! 🎉 Python 2.7 now builds on Windows.

Care to do the honors @pelson?

**Pull request merged**
