### PR TITLE
v5.9.6

### PR DESCRIPTION
**Pull request by thewchan**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by thewchan** [comment]
@conda-forge-admin, please rerender

**Comment by thewchan** [comment]
@jakirkham might need some help with win build error here

**Comment by thewchan** [comment]
looks like it's just that one pypy build for win @jakirkham should I just skip it or?

**Comment by jakirkham** [comment]
Thanks Matt! 🙏

This was targeting `main`. So I changed it to the `v5.9.6` branch

Unfortunately that made a mess of the commit history. Sorry about that 😞

When you have a chance, could you please rebase to cleanup the history? Ideally this just has the version bump (and maybe a re-render) as commits

Then we can dig into whatever we see on CI once that is done

**Comment by thewchan** [comment]
@jakirkham tried rebase and force-push, but history still look bad; maybe I can restart from the new v5.9.6 branch

**Pull request closed without merging**
