### PR TITLE
Update 4.4.2

### PR DESCRIPTION
**Pull request by gqmelo**
To be merged after https://github.com/conda-forge/psutil-feedstock/pull/10

### CODE REVIEW

**Comment by jakirkham** [comment]
This seems to be failing. Also feel free to rebase as the other one is merged.

**Comment by gqmelo** [comment]
Actually I had aborted the jobs as it would need a rebase anyway.

**Comment by jakirkham** [comment]
Ah ok.

**Comment by gqmelo** [comment]
@jakirkham, kind reminder

**Comment by ocefpaf** [comment]
@gqmelo if you are interested in this feedstock consider adding yourself as a maintainer.

**Comment by jakirkham** [comment]
Sorry was waiting for CIs and then it fell off my radar, @gqmelo. Thanks for merging @ocefpaf.

**Comment by gqmelo** [comment]
Thanks! Ok, I'll add me as maintainer to update next versions

**Pull request merged**
