### PR TITLE
freethreading support

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Support for freethreading was added in 6.0.0

### CODE REVIEW

**Comment by isuruf** [comment]
@jakirkham, can you review?

**Comment by jakirkham** [comment]
Thanks Isuru! 🙏

It looks like there are a couple patches that didn't make it into 6.0.0 that we may want to include:

* https://github.com/giampaolo/psutil/pull/2428
* https://github.com/giampaolo/psutil/pull/2442

**Comment by isuruf** [comment]
I added the first patch. The second one was needed for the first two rc builds and it isn't needed anymore because of https://github.com/python/cpython/pull/112778

**Comment by jakirkham** [comment]
Thanks Isuru! 🙏

Looking upstream am seeing this later change ( https://github.com/python/cpython/pull/115850 ), which suggests extensions need to pass `/DPy_GIL_DISABLED`. So am wondering if this is what the author of PR ( https://github.com/giampaolo/psutil/pull/2442 ) encountered

Admittedly I've not dug into this as much as you. So am open to trying things with the off chance this may need a follow up later

**Comment by isuruf** [comment]
No, the freethreaded build in conda-forge has
```
#ifndef Py_GIL_DISABLED
#define Py_GIL_DISABLED 1
#endif
```
so that macro is not required to be set.

**Comment by jakirkham** [comment]
Ah I see. [The `--disable-gil` flag we pass]( https://github.com/conda-forge/python-feedstock/blob/12d71f4a8841a10281c986e82fc4f7c3cab10329/recipe/build_base.bat#L48 ) will [ensure it is defined]( https://github.com/python/cpython/pull/115850/files#diff-4295039788386c2986b811f2a6b59cf088be59822b24b4f1243c9e9b184f65fbR680 )

**Comment by jakirkham** [comment]
Thanks again Isuru! 🙏

**Pull request merged**
