### PR TITLE
Bump to version 4.3.0

### PR DESCRIPTION
**Pull request by jakirkham**

### CODE REVIEW

**Comment by jakirkham** [comment]
Figure we should try merging PR ( https://github.com/conda-forge/psutil-feedstock/pull/7 ) first to ensure that we have version 4.2.0 on conda-forge.

**Comment by pelson** [comment]
:+1:

**Comment by jakirkham** [comment]
Rebased and removed WIP. As we already have 4.2.0, we should be fine to go ahead with 4.3.0.

**Comment by jakirkham** [comment]
Everything passes. As this is a simple version bump and have already got a +1, taking this in. Seems this has some pretty important fixes in it.

**Pull request merged**
